### ISSUE TITLE
JsonStreamListener has no attribute 'streaming_exception'

### ISSUE THREAD

**Issue by mansilla** [michaelbrooks/twitter-monitor#5]
Hi Michael, great work, this is a really useful library. Sadly I am having an issue when instantiating a `JsonStreamListener`. I am adapting some of my previous code like this

``` python
class CustomListener(twitter_monitor.JsonStreamListener):
    def __init__(self, tweets):
        self.tweets = tweets

    def on_status(self, status):
        print json.dumps(status, indent=3)
        process_stream(status,self.tweets) 

    def on_limit(self, track):
        print "Horrors, we lost %d tweets!" % track

class Twee(threading.Thread): 
    def __init__(self, termsFile, auth, tweets):
        self.termsFile = termsFile
        self.auth = auth
        self.tweets = tweets
        threading.Thread.__init__(self)

    def run(self):
        global exitFlag
        if not exitFlag:
            poll_interval = 15  # these are minutes, seconds?..
            listener = CustomListener(self.tweets)
            checker = twitter_monitor.checker.FileTermChecker(filename=self.termsFile)
            stream = twitter_monitor.DynamicTwitterStream(self.auth, listener, checker)
            while True:
                try:
                    stream.start_polling(poll_interval)
                except Exception as e:
                    print '[%s] :Error on stream:: %s, trying again...'%(str(datetime.datetime.now()),e)
                    time.sleep(3)
                    #break

```

And I am getting these errors when running my class instance:

``` log
[2015-08-19 14:09:12.018663] :Error on stream:: 'CustomListener' object has no attribute 'streaming_exception', trying again..
WARNING:twitter_monitor.stream:Stopping twitter stream...
[2015-08-19 14:09:16.078629] :Error on stream:: 'CustomListener' object has no attribute 'streaming_exception', trying again..
WARNING:twitter_monitor.stream:Stopping twitter stream...
(...)
ERROR:twitter_monitor.listener:Twitter returned error code 420
WARNING:twitter_monitor.stream:Stopping twitter stream...
[2015-08-19 14:09:44.257910] :Error on stream:: 'CustomListener' object has no attribute 'streaming_exception', trying again..
WARNING:twitter_monitor.stream:Stopping twitter stream...
[2015-08-19 14:09:52.289508] :Error on stream:: 'CustomListener' object has no attribute 'streaming_exception', trying again..
ERROR:twitter_monitor.listener:Twitter returned error code 420
ERROR:twitter_monitor.listener:Exception from stream!
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tweepy/streaming.py", line 239, in _run
    verify=self.verify)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Library/Python/2.7/site-packages/tweepy/streaming.py", line 286, in _run
    raise exception
ConnectionError: ('Connection aborted.', BadStatusLine("''",))

WARNING:twitter_monitor.stream:Stopping twitter stream...
WARNING:twitter_monitor.stream:Streaming exception: ('Connection aborted.', BadStatusLine("''",))
[2015-08-19 14:09:56.308247] :Error on stream:: ('Connection aborted.', BadStatusLine("''",)), trying again..
ERROR:twitter_monitor.listener:Twitter returned error code 420
WARNING:twitter_monitor.stream:Stopping twitter stream...
ERROR:twitter_monitor.listener:Twitter returned error code 420
ERROR:twitter_monitor.listener:Twitter returned error code 420
WARNING:twitter_monitor.stream:Stream exists but isn't running
WARNING:twitter_monitor.stream:Stopping twitter stream...
```

and so on... Weird thing is that occasionally I also get some statuses printed on the shell. Meaning my **_auth**_ is ok and the arriving exception is different. Any ideas whats going on? I have dive into the code and found this in the class definition

``` python
def on_exception(self, exception):
        """An exception occurred in the streaming thread"""
        logger.error('Exception from stream!', exc_info=True)
        self.streaming_exception = exception
```

which is initialised in `__init__` as `None`. So everything seems to be in order here..

**Comment by mansilla** [comment]
The obvious solution would be

```python
class CustomListener(twitter_monitor.JsonStreamListener):
    def __init__(self, tweets):
        self.tweets = tweets
        self.streaming_exception = None

    def on_status(self, status):
        print json.dumps(status, indent=3)
        process_stream(status,self.tweets) 

    def on_limit(self, track):
        print "Horrors, we lost %d tweets!" % track
```

and this solves the issue but still, no a clue why this is happening..

**Comment by michaelbrooks** [comment]
In Python you need to explicitly call through to the parent class's `__init__` method. See [this SO post](http://stackoverflow.com/questions/12701206/how-to-extend-python-class-init). So, that would be:

```python
class CustomListener(twitter_monitor.JsonStreamListener):
    def __init__(self, tweets):
        super(CustomListener, self).__init__()
        self.tweets = tweets
# etc.
```

Let me know if this fixes the problem!
